version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-api
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
      - mqtt
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongodb:27017/db
      MQTT_HOST: mqtt://mqtt:1883

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  mongo_data:
